### ISSUE TITLE
Does nothing without a camera

### ISSUE THREAD

**Issue by quozl** [sugarlabs/pointillism-activity#17]
Activity should explain why nothing happens.  The Level activity shows a message without an accelerometer.  The Record activity removes some features without a camera.

Activity may also offer a load image from Journal feature.

**Comment by srevinsaju** [comment]
@quozl , as part of GCI task, how would it be if I add an option to convert a selected image to Pointilism, so its useful for those systems without a camera too, the code is ready except for the chose file dialog on sugar

**Comment by quozl** [comment]
@srevinsaju, the feature you describe here would be an improvement, thanks.

However, I don't know of a GCI task that would cover it.

**Comment by srevinsaju** [comment]
@quozl : I am doing this with reference to `Pointillism activity without Camera` task.
I have added additional features, for _like an icing on cake_ :smile:

**Comment by quozl** [comment]
Thanks for reminding me.  I'd forgotten this was a task.  Don't forget to take the task in order to lock out any other students also taking it, otherwise we'll award it to whoever solves this first.  Off-topic for the issue though, so I'll hide this thread.
